name: Test Workflows
on:
  push:
    branches:
      - linus
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test a shell-script
        run: sh ./.github/scripts/test.sh
      - name: Github-Repository
        run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
