name: Test Workflows
on:
  push:
    branches:
      - linus
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test a shell-script
        run: sh ./.github/scripts/test.sh
      - name: Install Racket
        run: raco pkg install --deps search-auto scribble-math
      - name: Install TypeScript
        run: npm install -g typescript
      - name: Test Scribble-Plugin
        run: sh ./scribble-plugin/test.sh
      - name: Github-Repository
        run: echo "The ${{ github.repository }} repository has been cloned to the runner."
