name: Generate HTML & PDF
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.7
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: 'stable'
      - run: raco pkg install --deps search-auto scribble-math
      - name: Install TexLive
        run: sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra
      - name: Install TypeScript
        run: npm install -g typescript
      - name: Copying current version of Questionnaire.js
        run: cp dist/questionnaire.js .
      - name: Generate HTML
        run: raco scribble --htmls --dest output/html scribble-plugin/test.scrbl
      - name: Generate PDF
        run: raco scribble --pdf --dest output/pdf scribble-plugin/test.scrbl
      ##  run: sh ./scribble-plugin/test.sh
