name: Test Workflows
on:
  push:
    branches:
      - linus
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test a shell-script
        run: sh ./.github/scripts/test.sh
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.7
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: 'stable'
      - run: raco pkg install --deps search-auto scribble-math
      - name: Install TypeScript
        run: npm install -g typescript
      - name: build docs (from informatik-1-skript)
        run: |
          xvfb-run racket -l racket/gui -l- scribble/run    ++xref-in setup/xref load-collections-xref   --htmls --redirect-main http://docs.racket-lang.org/ script.scrbl
      - name: Test Scribble-Plugin
        run: sh ./scribble-plugin/test.sh
      - name: Github-Repository
        run: echo "The ${{ github.repository }} repository has been cloned to the runner."
