name: Releases
on:
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: Zipping /dist Directory
      run: zip -r release.zip dist
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        bodyFile: "CHANGELOG.md"
        token: ${{ secrets.GITHUB_TOKEN }}
